# Generated by Django 4.1.5 on 2023-02-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='herramientas',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='herramientas',
            field=models.ManyToManyField(to='proyectos.herramienta'),
        ),
    ]
